version: '3'

services:
  database:
    image: mysql:5.7
    volumes:
      - ./data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - internal
  prestashop:
    depends_on:
      - database
    image: prestashop/prestashop
    volumes: 
     - ./themes:/var/www/html/themes
     - ./modules:/var/www/html/modules
    ports:
     - "8088:80"
    restart: always
    environment:
      DB_SERVER: "database"
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWD: ${MYSQL_PASSWORD}
      PS_LANGUAGE: ${PS_LANGUAGE}
      PS_COUNTRY: ${PS_COUNTRY}
      PS_DEV_MODE: ${PS_DEV_MODE}
      PS_FOLDER_ADMIN: ${PS_FOLDER_ADMIN}
      PS_FOLDER_INSTALL: ${PS_FOLDER_INSTALL}
      ADMIN_MAIL: ${PS_ADMIN_MAIL}
      ADMIN_PASSWD: ${PS_ADMIN_PASSWORD}
      PS_INSTALL_AUTO: 1
      PS_DOMAIN: localhost
      PS_HANDLE_DYNAMIC_DOMAIN: 1
    networks:
      - internal
      - public
networks:
  internal:
  public: 
